default: &default
  adapter: postgresql
  encoding: unicode
  template: template0

development:
  <<: *default
  database: bsdports_development

test:
  <<: *default
  database: bsdports_test

production:
  <<: *default
  database: bsdports_production
  username: bsdports
  password: <%= ENV["BSDPORTS_DATABASE_PASSWORD"] %>

